image: python:alpine

before_script:
  - pip install mkdocs

pages:
  script:
  - curl https://gitlab.com/dark-crystal/introduction-to-dark-crystal/raw/master/README.md > docs/introduction.md
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
