site_name: Dark Crystal
site_url: https://dark-crystal.gitlab.io
nav:
  - 'Home': 'index.md'
  - 'Overview': 'introduction-to-dark-crystal.md'
  - 'Key Backup Protocol specification': 'protocol-specification.md'
  - 'Key Backup Message Schemas': 'message-schemas.md'
  - 'Key re-issuance using threshold signatures': 'threshold-signatures.md'
  - 'What is Secret sharing?': 'shamirs-secret-sharing.md'
  - 'User Interface recommendations': 'ui-recommendations.md'
  - 'Paper keys': 'paper-keys.md'
theme:
  name: null
  custom_dir: 'material/'
  language: en
  palette:
    primary: purple
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  logo:
  feature:
    tabs: false
  static_templates:
    - 404.html
