site_name: Dark Crystal
site_url: https://dark-crystal.gitlab.io
nav:
  - Home: index.md
  - Introduction: introduction-to-dark-crystal/README.md
  # - Protocol specification: protocol-specification.md
  # - Threshold signatures: threshold-signatures.md
  - Secret sharing: shamirs-secret-sharing.md
theme:
  name: null
  custom_dir: 'material/'
  language: en
  palette:
    primary: purple
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  logo:
  feature:
    tabs: false
  static_templates:
    - 404.html
